env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: hello-world-server
  ECS_SERVICE: hello-world-service
  ECS_CLUSTER: hello-world-cluster
  ECS_TASK_DEFINITION: task-definition.json
  CONTAINER_NAME: hello-world-container